# Generated by Django 2.1 on 2018-08-24 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(db_column='aid', primary_key=True, serialize=False, verbose_name='area_id')),
                ('name', models.CharField(db_column='rname', max_length=20, verbose_name='risk_name')),
            ],
            options={
                'db_table': 't_area',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.IntegerField(db_column='rid', primary_key=True, serialize=False, verbose_name='risk_id')),
                ('name', models.CharField(db_column='rname', max_length=20, verbose_name='risk_name')),
                ('desp', models.CharField(db_column='rdesp', max_length=50, verbose_name='risk_description')),
            ],
            options={
                'db_table': 't_risk',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='risk',
            field=models.ForeignKey(db_column='rid', on_delete=django.db.models.deletion.PROTECT, to='risk.Risk', verbose_name='risk_level'),
        ),
    ]
