# Generated by Django 2.1 on 2018-08-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='level',
            field=models.IntegerField(db_column='rlevel', default=0, verbose_name='risk_level'),
        ),
    ]
