# Generated by Django 2.1 on 2018-08-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(db_column='city_id', primary_key=True, serialize=False, verbose_name='city_id')),
                ('name', models.CharField(db_column='city_name', max_length=50, verbose_name='city_name')),
                ('parent', models.CharField(db_column='parent_city', default='Melbourne', max_length=50, verbose_name='parent_city')),
                ('state', models.CharField(db_column='state', default='Victoria', max_length=50, verbose_name='state')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 't_city',
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(db_column='suburb_id', primary_key=True, serialize=False, verbose_name='suburb_id')),
                ('name', models.CharField(db_column='suburb_name', max_length=50, verbose_name='suburb_name')),
                ('postcode', models.CharField(db_column='postcode', max_length=4, verbose_name='postcode')),
                ('good_count', models.IntegerField(db_column='good_count', default=0, verbose_name='good_count')),
                ('bad_count', models.IntegerField(db_column='bad_count', default=0, verbose_name='bad_count')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='comment.City', verbose_name='city')),
            ],
            options={
                'verbose_name': 'suburb',
                'verbose_name_plural': 'suburbs',
                'db_table': 't_suburb',
            },
        ),
    ]
