# Generated by Django 2.1 on 2018-09-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_cityrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburb',
            name='star_count',
            field=models.IntegerField(db_column='star_count', default=0, verbose_name='star_count'),
        ),
        migrations.AddField(
            model_name='suburb',
            name='star_total',
            field=models.FloatField(db_column='star_total', default=0, verbose_name='star_total'),
        ),
    ]
